export const mockDevices = [
    {
      id: 1,
      name: "Server-01",
      type: "Server",
      ip: "192.168.1.10",
      status: "Online",
      lastSeen: "1 min ago",
    },
    {
      id: 2,
      name: "Workstation-Recepție",
      type: "Workstation",
      ip: "192.168.1.21",
      status: "Online",
      lastSeen: "30 sec ago",
    },
    {
      id: 3,
      name: "Router-Core",
      type: "Router",
      ip: "192.168.1.1",
      status: "Warning",
      lastSeen: "10 sec ago",
    },
    {
      id: 4,
      name: "Printer-HR",
      type: "Printer",
      ip: "192.168.1.50",
      status: "Offline",
      lastSeen: "12 min ago",
    },
    {
      id: 5,
      name: "Server-DB",
      type: "Server",
      ip: "192.168.1.11",
      status: "Online",
      lastSeen: "2 min ago",
    },
    {
      id: 6,
      name: "PC-Contabilitate",
      type: "Workstation",
      ip: "192.168.1.32",
      status: "Offline",
      lastSeen: "18 min ago",
    },
  ];